# This is an auto generated Dockerfile for ros:ros-base
# https://github.com/osrf/docker_images/blob/master/ros/melodic/ubuntu/bionic/ros-base/Dockerfile
FROM broerkens/jetson-ros:melodic-ros-core-bionic

# install ros packages
RUN apt-get update && apt-get install -y \
    ros-melodic-ros-base=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

