# This is an auto generated Dockerfile for ros:desktop-full
# https://github.com/osrf/docker_images/blob/master/ros/melodic/ubuntu/bionic/desktop-full/Dockerfile
FROM broerkens/jetson-ros:melodic-desktop-bionic

# install ros packages
RUN apt-get update && apt-get install -y \
    ros-melodic-desktop-full=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

