# This is an auto generated Dockerfile for ros:perception
# https://github.com/osrf/docker_images/blob/master/ros/melodic/ubuntu/bionic/perception/Dockerfile
FROM broerkens/jetson-ros:melodic-ros-base-bionic

# install ros packages
RUN apt-get update && apt-get install -y \
    ros-melodic-perception=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

