# This is an auto generated Dockerfile for ros:desktop
# https://github.com/osrf/docker_images/blob/master/ros/melodic/ubuntu/bionic/desktop/Dockerfile

FROM broerkens/jetson-ros:melodic-robot-bionic

# install ros packages
RUN apt-get update && apt-get install -y \
    ros-melodic-desktop=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

